### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by volodymyr-kushnir** [kuts-denys/BSA-first-task#3]
Hi.
You're doing great — *"the force is strong with this one"* — referencing issues with commit numbers will not go unnoticed.
Still, may I suggest adding a **README.md** with a short description of this repository and links to the articles?
That would help to surf the repository with GitHub.

**Comment by kuts-denys** [comment]
Thank you for your feedback! README.md is added.

**Comment by volodymyr-kushnir** [comment]
![image](https://cloud.githubusercontent.com/assets/10290626/26284486/3e81c1ee-3e45-11e7-8ec2-867969d5b961.png)
@kuts-denys на рахунок гілок — на скріншоті те, що я бачу. Проблема мені зрозуміла, але я б ще попросив тебе заскріншотити сюди твій `git reflog`, для ясності картини.

**Comment by kuts-denys** [comment]
![otakot](https://i.gyazo.com/47623f83dc431b79b0e80072e99181c2.png)

Відразу поясню наявність "pull": то я вирішив перший комент запилити локально та закомітити з консолі, а комент до цього комента (тобто "мій") я додав з інтерфейсу гітхабу - на цьому віддаленому репозиторії., а потів оновив свій локальний пулом и продовжив. Так я здається два рази зробив (чому б і ні я подумав :D). 

Гілки мої не видно я так розумію тому що я мерджив локально, і тут це чомусь ніяк не відображається.

**Comment by volodymyr-kushnir** [comment]
@kuts-denys "чому б і ні" то нормальний підхід, по руках за таке не б'ють (окрім випадків, коли б'ють), але ж все вийшло окей, то чому б і ні.
І гілки я бачу — он є мердж `lllyaEvseev-comment`, потім створення `stepan-comment`, який був змерджений через **Pull Request** тут на **GitHub**'і, і потім створення `my-comment` локально і мердж її локально. Всьо в порядку.

**Comment by kuts-denys** [comment]
Це добре!) А от таке питання: що робити з гілками, які я локально вже змерджив (та видалив), а тут вони залишилися? Першу таку гілку я і тут видалив, а наступну залишив, думаючи що може так буде видно процес, але судячи з вашого скріна - не вийшло. Теж напевно видаляти?

**Comment by volodymyr-kushnir** [comment]
> з вашого скріна

З *твого скріна. Ти — "ти", і я — "ти".
А як захочеш @kuts-denys, це ж твій репозиторій. Хочеш видаляй, а хочеш, то й лиши. Як правило змерджені гілки видаляються. Наприклад, `feature/awesome-editor` змерджена в `master`, а значить впроваджена і тому наступна робота в тому ж напрямку буде в гілці `patch/awesome-editor` чи `hotfix/awesome-editor`. Інакше логіка буде дивною, якшо ми ніби релізнули функціонал, але продовжуємо його допилювати в тій самій гілці — для чого релізнули тоді? Але це все від команди залежить, тому — як захочеш.
Наприклад, інша ситуація — в мене є гілка `update/dependencies` і я в ній регулярно тестую нові npm-пакети і якщо все окей, то оновлюю версії в package.json і тоді мерджу до `master`. Чого б я її видаляв і створював кожен тиждень? Таке.

**Comment by kuts-denys** [comment]
Ага, зрозуміло, дякую за роз'яснення.
